/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule



module SumadorRestador4bits (
  input A0,
  input B0,
  input Cin,
  input B2,
  input B1,
  input B3,
  input A1,
  input A2,
  input A3,
  output S0,
  output Cout,
  output S1,
  output S2,
  output S3
);
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  assign s4 = (B0 ^ Cin);
  assign s6 = (B1 ^ Cin);
  assign s8 = (B2 ^ Cin);
  assign s10 = (B3 ^ Cin);
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i0 (
    .a( A0 ),
    .b( s4 ),
    .c_i( Cin ),
    .s( S0 ),
    .c_o( s5 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i1 (
    .a( A1 ),
    .b( s6 ),
    .c_i( s5 ),
    .s( S1 ),
    .c_o( s7 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i2 (
    .a( A2 ),
    .b( s8 ),
    .c_i( s7 ),
    .s( S2 ),
    .c_o( s9 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i3 (
    .a( A3 ),
    .b( s10 ),
    .c_i( s9 ),
    .s( S3 ),
    .c_o( s11 )
  );
  assign Cout = (s11 ^ Cin);
endmodule
