/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module SumadorRestador (
  input A0,
  input B0,
  input A1,
  input A2,
  input A3,
  input B1,
  input B2,
  input B3,
  input Cin,
  output S0,
  output S1,
  output S2,
  output S3,
  output Cout
);
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  assign s4 = (B0 ^ Cin);
  assign s6 = (B1 ^ Cin);
  assign s8 = (B2 ^ Cin);
  assign s10 = (B3 ^ Cin);
  assign S0 = ~ (Cin ^ ~ (s4 ^ A0));
  assign s5 = ((A0 & s4) | (A0 & Cin) | (s4 & Cin));
  assign S1 = ~ (s5 ^ ~ (s6 ^ A1));
  assign s7 = ((A1 & s6) | (A1 & s5) | (s6 & s5));
  assign S2 = ~ (s7 ^ ~ (s8 ^ A2));
  assign s9 = ((A2 & s8) | (A2 & s7) | (s8 & s7));
  assign S3 = ~ (s9 ^ ~ (s10 ^ A3));
  assign Cout = (((A3 & s10) | (A3 & s9) | (s10 & s9)) ^ Cin);
endmodule
